# Generated by Django 4.2 on 2023-04-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_cows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Farmers',
        ),
    ]
